  # YAML Reference http://www.yaml.org/refcard.html
continuum:
  debug: true
  maxNumberOfCoresToUse: 4
  disableClustering: false
  cluster:
    discoveryType: SHAREDFS
    sharedFsPath: /tmp/structures-sharedfs

logging:
  level:
    org:
      kinotic: TRACE
    io:
      vertx: DEBUG

spring:
  devtools:
    livereload:
      port: 35730
